const cityOptions = [
  {
    label: '北部',
    options: [
      { label: '臺北市', value: 'Taipei' },
      { label: '新北市', value: 'NewTaipei' },
      { label: '基隆市', value: 'Keelung' },
      { label: '桃園市', value: 'Taoyuan' },
      { label: '宜蘭縣', value: 'YilanCounty' },
      { label: '新竹市', value: 'Hsinchu' },
      { label: '新竹縣', value: 'HsinchuCounty' },
    ],
  },
  {
    label: '中部',
    options: [
      { label: '臺中市', value: 'Taichung' },
      { label: '苗栗縣', value: 'MiaoliCounty' },
      { label: '彰化縣', value: 'ChanghuaCounty' },
      { label: '南投縣', value: 'NantouCounty' },
      { label: '雲林縣', value: 'YunlinCounty' },
    ],
  },
  {
    label: '南部',
    options: [
      { label: '高雄市', value: 'Kaohsiung' },
      { label: '嘉義市', value: 'Chiayi' },
      { label: '嘉義縣', value: 'ChiayiCounty' },
      { label: '臺南市', value: 'Tainan' },
      { label: '屏東縣', value: 'PingtungCounty' },
    ],
  },
  {
    label: '東部',
    options: [
      { label: '臺東縣', value: 'TaitungCounty' },
      { label: '花蓮縣', value: 'HualienCounty' },
    ],
  },
  {
    label: '離島',
    options: [
      { label: '澎湖縣', value: 'PenghuCounty' },
      { label: '金門縣', value: 'KinmenCounty' },
      { label: '連江縣', value: 'LienchiangCounty' },
    ],
  },
];

export default cityOptions;


export function districtsOption(city) {
  if(city === 'Taipei' || city === '臺北市'){
    return ['松山區', '信義區', '大安區', '中山區', '中正區', '大同區', '萬華區', '文山區', '南港區', '內湖區', '士林區', '北投區'];
  }else if(city === 'NewTaipei' || city === '新北市'){
    return ['板橋區','三重區','中和區','永和區','新莊區','新店區','樹林區','鶯歌區','三峽區','淡水區','汐止區','瑞芳區','土城區','蘆洲區','五股區','泰山區','林口區','深坑區','石碇區','坪林區','三芝區','石門區','八里區','平溪區','雙溪區','貢寮區','金山區','萬里區','烏來區'];
  }else if (city === 'Keelung' || city === '基隆市'){
    return ['中正區','七堵區','暖暖區','仁愛區','中山區','安樂區','信義區']
  }else if(city === 'Taoyuan' || city === '桃園市'){
    return ['桃園區','中壢區','大溪區','楊梅區','蘆竹區','大園區','龜山區','八德區','龍潭區','平鎮區','新屋區','觀音區','復興區'];
  }else if(city === 'YilanCounty' || city === '宜蘭縣'){
    return ['宜蘭市','羅東鎮','蘇澳鎮','頭城鎮','礁溪鄉','壯圍鄉','員山鄉','冬山鄉','五結鄉','三星鄉','大同鄉','南澳鄉'];
  }else if(city === 'Hsinchu' || city === '新竹市'){
    return ['東區','北區','香山區'];
  }else if(city === 'HsinchuCounty' || city === '新竹縣'){
    return ['竹北市','關西鎮','新埔鎮','竹東鎮','湖口鄉','橫山鄉','新豐鄉','芎林鄉','寶山鄉','北埔鄉','峨眉鄉','尖石鄉','五峰鄉'];
  }else if(city === 'Taichung' || city === '臺中市'){
    return ['北屯區','西屯區','南屯區','豐原區','東勢區','大甲區','清水區','沙鹿區','梧棲區','后里區','神岡區','潭子區','大雅區','新社區','石岡區','外埔區','大安區','烏日區','大肚區','龍井區','霧峰區','太平區','大里區','和平區','中區','東區','南區','西區','北區'];
  }else if(city === 'MiaoliCounty' || city === '苗栗縣'){
    return ['苗栗市','頭份市','苑裡鎮','通霄鎮','竹南鎮','後龍鎮','卓蘭鎮','大湖鄉','公館鄉','銅鑼鄉','南庄鄉','頭屋鄉','三義鄉','西湖鄉','造橋鄉','三灣鄉','獅潭鄉','泰安鄉'];
  }else if(city === 'ChanghuaCounty' || city === '彰化縣'){
    return ['彰化市','員林市','鹿港鎮','和美鎮','北斗鎮','溪湖鎮','田中鎮','二林鎮','線西鄉','伸港鄉','福興鄉','秀水鄉','花壇鄉','芬園鄉','大村鄉','埔鹽鄉','埔心鄉','永靖鄉','社頭鄉','二水鄉','田尾鄉','埤頭鄉','芳苑鄉','大城鄉','竹塘鄉','溪州鄉'];
  }else if(city === 'NantouCounty' || city === '南投縣'){
    return ['南投市','埔里鎮','草屯鎮','竹山鎮','集集鎮','名間鄉','鹿谷鄉','中寮鄉','魚池鄉','國姓鄉','水里鄉','信義鄉','仁愛鄉'];
  }else if(city === 'YunlinCounty' || city === '雲林縣'){
    return ['斗六市','斗南鎮','虎尾鎮','西螺鎮','土庫鎮','北港鎮','古坑鄉','大埤鄉','莿桐鄉','林內鄉','二崙鄉','崙背鄉','麥寮鄉','東勢鄉','褒忠鄉','臺西鄉','元長鄉','四湖鄉','口湖鄉','水林鄉'];
  }else if(city === 'Kaohsiung' || city === '高雄市'){
    return ['鹽埕區','鼓山區','左營區','楠梓區','三民區','新興區','前金區','苓雅區','前鎮區','旗津區','小港區','鳳山區','林園區','大寮區','大樹區','大社區','仁武區','鳥松區','岡山區','橋頭區','燕巢區','田寮區','阿蓮區','路竹區','湖內區','茄萣區','永安區','彌陀區','梓官區','旗山區','美濃區','六龜區','甲仙區','杉林區','內門區','茂林區','桃源區','那瑪夏區'];
  }else if(city === 'Chiayi' || city === '嘉義市'){
    return ['東區','西區'];
  }else if(city === 'ChiayiCounty' || city === '嘉義縣'){
    return ['太保市','朴子市','布袋鎮','大林鎮','民雄鄉','溪口鄉','新港鄉','六腳鄉','東石鄉','義竹鄉','鹿草鄉','水上鄉','中埔鄉','竹崎鄉','梅山鄉','番路鄉','大埔鄉','阿里山鄉'];
  }else if(city === 'Tainan' || city === '臺南市'){
    return ['新營區','鹽水區','白河區','柳營區','後壁區','東山區','麻豆區','下營區','六甲區','官田區','大內區','佳里區','學甲區','西港區','七股區','將軍區','北門區','新化區','善化區','新市區','安定區','山上區','玉井區','楠西區','南化區','左鎮區','仁德區','歸仁區','關廟區','龍崎區','永康區','安南區','安平區','中西區','東區','南區','北區'];
  }else if(city === 'PingtungCounty' || city === '屏東縣'){
    return ['屏東市','潮州鎮','東港鎮','恆春鎮','萬丹鄉','長治鄉','麟洛鄉','九如鄉','里港鄉','鹽埔鄉','高樹鄉','萬巒鄉','內埔鄉','竹田鄉','新埤鄉','枋寮鄉','新園鄉','崁頂鄉','林邊鄉','南州鄉','佳冬鄉','琉球鄉','車城鄉','滿州鄉','枋山鄉','霧臺鄉','瑪家鄉','泰武鄉','來義鄉','春日鄉','獅子鄉','牡丹鄉','三地門鄉'];
  }else if(city === 'TaitungCounty' || city === '臺東縣'){
    return ['臺東市','成功鎮','關山鎮','卑南鄉','大武鄉','太麻里鄉','東河鄉','長濱鄉','鹿野鄉','池上鄉','綠島鄉','延平鄉','海端鄉','達仁鄉','金峰鄉','蘭嶼鄉'];
  }else if(city === 'HualienCounty' || city === '花蓮縣'){
    return ['花蓮市','鳳林鎮','玉里鎮','新城鄉','吉安鄉','壽豐鄉','光復鄉','豐濱鄉','瑞穗鄉','富里鄉','秀林鄉','萬榮鄉','卓溪鄉'];
  }else if(city === 'PenghuCounty' || city === '澎湖縣'){
    return ['馬公市','湖西鄉','白沙鄉','西嶼鄉','望安鄉','七美鄉'];
  }else if(city === 'KinmenCounty' || city === '金門縣'){
    return ['金城鎮','金湖鎮','金沙鎮','金寧鄉','烈嶼鄉','烏坵鄉'];
  }else if(city === 'LienchiangCounty' || city === '連江縣'){
    return ['南竿鄉','北竿鄉','莒光鄉','東引鄉'];
  }
};

export function zipCodeSearch(zipCode) {
  switch (zipCode) {
    case '100':
      return '中正區';
    case '103':
      return '大同區';
    case '104':
      return '中山區';
    case '105':
      return '松山區';
    case '106':
      return '大安區';
    case '108':
      return '萬華區';
    case '110':
      return '信義區';
    case '111':
      return '士林區';
    case '112':
      return '北投區';
    case '114':
      return '內湖區';
    case '115':
      return '南港區';
    case '116':
      return '文山區';
    case '207':
      return '萬里區';
    case '208':
      return '文山區';
    case '220':
      return '板橋區';
    case '221':
      return '汐止區';
    case '222':
      return '深坑區';
    case '223':
      return '石碇區';
    case '224':
      return '瑞芳區';
    case '226':
      return '平溪區';
    case '227':
      return '雙溪區';
    case '228':
      return '貢寮區';
    case '231':
      return '新店區';
    case '232':
      return '坪林區';
    case '233':
      return '烏來區';
    case '234':
      return '永和區';
    case '235':
      return '中和區';
    case '236':
      return '土城區';
    case '237':
      return '三峽區';
    case '238':
      return '樹林區';
    case '239':
      return '鶯歌區';
    case '241':
      return '三重區';
    case '242':
      return '新莊區';
    case '243':
      return '泰山區';
    case '244':
      return '林口區';
    case '247':
      return '蘆洲區';
    case '248':
      return '五股區';
    case '249':
      return '八里區';
    case '251':
      return '淡水區';
    case '252':
      return '三芝區';
    case '253':
      return '石門區';
    case '200':
      return '仁愛區';
    case '201':
      return '信義區';
    case '202':
      return '中正區';
    case '203':
      return '中山區';
    case '204':
      return '安樂區';
    case '205':
      return '暖暖區';
    case '206':
      return '七堵區';
    case '260':
      return '宜蘭市';
    case '261':
      return '頭城鎮';
    case '262':
      return '礁溪鄉';
    case '263':
      return '壯圍鄉';
    case '264':
      return '員山鄉';
    case '265':
      return '羅東鎮';
    case '266':
      return '三星鄉';
    case '267':
      return '大同鄉';
    case '268':
      return '五結鄉';
    case '269':
      return '冬山鄉';
    case '270':
      return '蘇澳鎮';
    case '272':
      return '南澳鄉';
    case '209':
      return '南竿鄉';
    case '210':
      return '北竿鄉';
    case '211':
      return '莒光鄉';
    case '212':
      return '東引鄉';
    case '302':
      return '竹北市';
    case '303':
      return '湖口鄉';
    case '304':
      return '新豐鄉';
    case '305':
      return '新埔鎮';
    case '306':
      return '關西鎮';
    case '307':
      return '芎林鄉';
    case '308':
      return '寶山鄉';
    case '310':
      return '竹東鎮';
    case '311':
      return '五峰鄉';
    case '312':
      return '橫山鄉';
    case '313':
      return '尖石鄉';
    case '314':
      return '北埔鄉';
    case '315':
      return '峨眉鄉';
    case '320':
      return '中壢區';
    case '324':
      return '平鎮區';
    case '325':
      return '龍潭區';
    case '326':
      return '楊梅區';
    case '327':
      return '新屋區';
    case '328':
      return '觀音區';
    case '330':
      return '桃園區';
    case '333':
      return '龜山區';
    case '334':
      return '八德區';
    case '335':
      return '大溪區';
    case '336':
      return '復興區';
    case '337':
      return '大園區';
    case '338':
      return '蘆竹區';
    case '350':
      return '竹南鎮';
    case '351':
      return '頭份市';
    case '352':
      return '三灣鄉';
    case '353':
      return '南庄鄉';
    case '354':
      return '獅潭鄉';
    case '356':
      return '後龍鎮';
    case '357':
      return '通霄鎮';
    case '358':
      return '苑裡鎮';
    case '360':
      return '苗栗市';
    case '361':
      return '造橋鄉';
    case '362':
      return '頭屋鄉';
    case '363':
      return '公館鄉';
    case '364':
      return '大湖鄉';
    case '365':
      return '泰安鄉';
    case '366':
      return '銅鑼鄉';
    case '367':
      return '三義鄉';
    case '368':
      return '西湖鄉';
    case '369':
      return '卓蘭鎮';
    case '400':
      return '中區';
    case '401':
      return '東區';
    case '402':
      return '南區';
    case '403':
      return '西區';
    case '404':
      return '北區';
    case '406':
      return '北屯區';
    case '407':
      return '西屯區';
    case '408':
      return '南屯區';
    case '411':
      return '太平區';
    case '412':
      return '大里區';
    case '413':
      return '霧峰區';
    case '414':
      return '烏日區';
    case '420':
      return '豐原區';
    case '421':
      return '后里區';
    case '422':
      return '石岡區';
    case '423':
      return '東勢區';
    case '424':
      return '和平區';
    case '426':
      return '新社區';
    case '427':
      return '潭子區';
    case '428':
      return '大雅區';
    case '429':
      return '神岡區';
    case '432':
      return '大肚區';
    case '433':
      return '沙鹿區';
    case '434':
      return '龍井區';
    case '435':
      return '梧棲區';
    case '436':
      return '清水區';
    case '437':
      return '大甲區';
    case '438':
      return '外埔區';
    case '439':
      return '大安區';
    case '500':
      return '彰化市';
    case '502':
      return '芬園鄉';
    case '503':
      return '花壇鄉';
    case '504':
      return '秀水鄉';
    case '505':
      return '鹿港鎮';
    case '506':
      return '福興鄉';
    case '507':
      return '線西鄉';
    case '508':
      return '和美鎮';
    case '509':
      return '伸港鄉';
    case '510':
      return '員林鎮';
    case '511':
      return '社頭鄉';
    case '512':
      return '永靖鄉';
    case '513':
      return '埔心鄉';
    case '514':
      return '溪湖鎮';
    case '515':
      return '大村鄉';
    case '516':
      return '埔鹽鄉';
    case '520':
      return '田中鎮';
    case '521':
      return '北斗鎮';
    case '522':
      return '田尾鄉';
    case '523':
      return '埤頭鄉';
    case '524':
      return '溪州鄉';
    case '525':
      return '竹塘鄉';
    case '526':
      return '二林鎮';
    case '527':
      return '大城鄉';
    case '528':
      return '芳苑鄉';
    case '530':
      return '二水鄉';
    case '540':
      return '南投市';
    case '541':
      return '中寮鄉';
    case '542':
      return '草屯鎮';
    case '544':
      return '國姓鄉';
    case '545':
      return '埔里鎮';
    case '546':
      return '仁愛鄉';
    case '551':
      return '名間鄉';
    case '552':
      return '集集鎮';
    case '553':
      return '水里鄉';
    case '555':
      return '魚池鄉';
    case '556':
      return '信義鄉';
    case '557':
      return '竹山鎮';
    case '558':
      return '鹿谷鄉';
    case '602':
      return '番路鄉';
    case '603':
      return '梅山鄉';
    case '604':
      return '竹崎鄉';
    case '605':
      return '阿里山';
    case '606':
      return '中埔鄉';
    case '607':
      return '大埔鄉';
    case '608':
      return '水上鄉';
    case '558':
      return '鹿谷鄉';
    case '611':
      return '鹿草鄉';
    case '612':
      return '太保市';
    case '613':
      return '朴子市';
    case '614':
      return '東石鄉';
    case '615':
      return '六腳鄉';
    case '616':
      return '新港鄉';
    case '621':
      return '民雄鄉';
    case '622':
      return '大林鎮';
    case '623':
      return '溪口鄉';
    case '624':
      return '義竹鄉';
    case '625':
      return '布袋鎮';
    case '630':
      return '斗南鎮';
    case '631':
      return '大埤鄉';
    case '632':
      return '虎尾鎮';
    case '633':
      return '土庫鎮';
    case '634':
      return '褒忠鄉';
    case '635':
      return '東勢鄉';
    case '636':
      return '臺西鄉';
    case '637':
      return '崙背鄉';
    case '638':
      return '麥寮鄉';
    case '640':
      return '斗六市';
    case '643':
      return '林內鄉';
    case '646':
      return '古坑鄉';
    case '647':
      return '莿桐鄉';
    case '648':
      return '西螺鎮';
    case '649':
      return '二崙鄉';
    case '651':
      return '北港鎮';
    case '652':
      return '水林鄉';
    case '653':
      return '口湖鄉';
    case '654':
      return '四湖鄉';
    case '655':
      return '元長鄉';
    case '700':
      return '中西區';
    case '701':
      return '東區';
    case '702':
      return '南區';
    case '704':
      return '北區';
    case '708':
      return '安平區';
    case '709':
      return '安南區';
    case '710':
      return '永康區';
    case '711':
      return '歸仁區';
    case '712':
      return '新化區';
    case '713':
      return '左鎮區';
    case '714':
      return '玉井區';
    case '715':
      return '楠西區';
    case '716':
      return '南化區';
    case '717':
      return '仁德區';
    case '718':
      return '關廟區';
    case '719':
      return '龍崎區';
    case '720':
      return '官田區';
    case '721':
      return '麻豆區';
    case '722':
      return '佳里區';
    case '723':
      return '西港區';
    case '724':
      return '七股區';
    case '725':
      return '將軍區';
    case '726':
      return '學甲區';
    case '727':
      return '七股區';
    case '727':
      return '北門區';
    case '730':
      return '新營區';
    case '731':
      return '後壁區';
    case '732':
      return '白河區';
    case '733':
      return '東山區';
    case '734':
      return '六甲區';
    case '735':
      return '下營區';
    case '736':
      return '柳營區';
    case '737':
      return '鹽水區';
    case '741':
      return '善化區';
    case '742':
      return '大內區';
    case '743':
      return '山上區';
    case '744':
      return '新市區';
    case '745':
      return '安定區';
    case '800':
      return '新興區';
    case '801':
      return '前金區';
    case '802':
      return '苓雅區';
    case '803':
      return '鹽埕區';
    case '804':
      return '鼓山區';
    case '805':
      return '旗津區';
    case '806':
      return '前鎮區';
    case '807':
      return '三民區';
    case '811':
      return '楠梓區';
    case '812':
      return '小港區';
    case '813':
      return '左營區';
    case '814':
      return '仁武區';
    case '815':
      return '大社區';
    case '820':
      return '岡山區';
    case '821':
      return '路竹區';
    case '823':
      return '田寮區';
    case '824':
      return '燕巢區';
    case '825':
      return '橋頭區';
    case '826':
      return '梓官區';
    case '827':
      return '彌陀區';
    case '828':
      return '永安區';
    case '829':
      return '湖內區';
    case '830':
      return '鳳山區';
    case '831':
      return '大寮區';
    case '832':
      return '林園區';
    case '833':
      return '鳥松區';
    case '840':
      return '大樹區';
    case '842':
      return '旗山區';
    case '843':
      return '美濃區';
    case '844':
      return '六龜區';
    case '845':
      return '內門區';
    case '846':
      return '杉林區';
    case '847':
      return '甲仙區';
    case '848':
      return '桃源區';
    case '849':
      return '那瑪夏區';
    case '851':
      return '茂林區';
    case '852':
      return '茄萣區';
    case '900':
      return '屏東市';
    case '901':
      return '三地門';
    case '902':
      return '霧臺鄉';
    case '903':
      return '瑪家鄉';
    case '904':
      return '九如鄉';
    case '905':
      return '里港鄉';
    case '906':
      return '高樹鄉';
    case '907':
      return '鹽埔鄉';
    case '908':
      return '長治鄉';
    case '909':
      return '麟洛鄉';
    case '911':
      return '竹田鄉';
    case '912':
      return '內埔鄉';
    case '913':
      return '萬丹鄉';
    case '920':
      return '潮州鎮';
    case '921':
      return '泰武鄉';
    case '922':
      return '來義鄉';
    case '923':
      return '萬巒鄉';
    case '924':
      return '崁頂鄉';
    case '925':
      return '新埤鄉';
    case '926':
      return '南州鄉';
    case '927':
      return '林邊鄉';
    case '928':
      return '東港鎮';
    case '929':
      return '琉球鄉';
    case '931':
      return '佳冬鄉';
    case '932':
      return '新園鄉';
    case '940':
      return '枋寮鄉';
    case '941':
      return '枋山鄉';
    case '942':
      return '春日鄉';
    case '943':
      return '獅子鄉';
    case '944':
      return '車城鄉';
    case '945':
      return '牡丹鄉';
    case '946':
      return '恆春鎮';
    case '947':
      return '滿州鄉';
    case '880':
      return '馬公市';
    case '881':
      return '西嶼鄉';
    case '882':
      return '望安鄉';
    case '883':
      return '七美鄉';
    case '884':
      return '白沙鄉';
    case '885':
      return '湖西鄉';
    case '890':
      return '金沙鎮';
    case '891':
      return '金湖鎮';
    case '892':
      return '金寧鄉';
    case '893':
      return '金城鎮';
    case '894':
      return '烈嶼鄉';
    case '896':
      return '烏坵鄉';
    case '950':
      return '臺東市';
    case '951':
      return '綠島鄉';
    case '952':
      return '蘭嶼鄉';
    case '953':
      return '延平鄉';
    case '954':
      return '卑南鄉';
    case '955':
      return '鹿野鄉';
    case '956':
      return '關山鎮';
    case '957':
      return '海端鄉';
    case '958':
      return '池上鄉';
    case '959':
      return '東河鄉';
    case '961':
      return '成功鎮';
    case '962':
      return '長濱鄉';
    case '963':
      return '太麻里';
    case '964':
      return '金峰鄉';
    case '965':
      return '大武鄉';
    case '966':
      return '達仁鄉';
    case '970':
      return '花蓮市';
    case '971':
      return '新城鄉';
    case '972':
      return '秀林鄉';
    case '973':
      return '吉安鄉';
    case '974':
      return '壽豐鄉';
    case '975':
      return '鳳林鎮';
    case '976':
      return '光復鄉';
    case '977':
      return '豐濱鄉';
    case '978':
      return '瑞穗鄉';
    case '979':
      return '萬榮鄉';
    case '981':
      return '玉里鎮';
    case '982':
      return '卓溪鄉';
    case '983':
      return '富里鄉';
  }
}